### ISSUE TITLE
This include 'simple_knn._C' ?

### ISSUE THREAD

**Issue by WhiteKnight666** [camenduru/simple-knn#1]
E:\Stable diffusion\comfyui\.ext\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "E:\Stable diffusion\comfyui\nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Stable diffusion\comfyui\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable diffusion\comfyui\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Stable diffusion\comfyui\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 48, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "E:\Stable diffusion\comfyui\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 11, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "E:\Stable diffusion\comfyui\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 28, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn._C'

Cannot import E:\Stable diffusion\comfyui\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'simple_knn._C'

I first meet this issue...

**Comment by MAXNORM8650** [comment]
I am also having the same issue.  Solution is first "git submodule add --force https://github.com/camenduru/simple-knn" then make a "__init__.py" file having "from . import _C
" and finally "pip install e ."  inside simple-knn module
